config/routes.rb
Gestorlcc::Application.routes.draw do

  resources :periodos,:peticionlabs,:solicitudlabs, :solicitudlabexas

  resources :dias, :horarios, :horasexas, :peticions, :solicitudrecursos

  resources :titulacions,:recursos, :laboratorios, :asignaturas,:usuarios
  resource :solicitar, :session, :inicio, :userinicio, :dato, :solicitudrecurso
  resources :solicitudrecursousuarios, :solicitudusuariolabs,:solicitudusuariolabexas

  get 'usuarios/:id/cambiar', :to => 'usuarios#cambiar' 

  

root :to => 'sessions#index'

get 'anonimo/new', :to=>'anonimo#new'
get 'anonimo/general', :to=>'anonimo#general'
get 'anonimo/labgeneral', :to=>'anonimo#labgeneral'
get 'estadisticas/periodo_lectivo', :to=>'estadisticas#periodo_lectivo'
get 'estadisticas/periodo_examenes', :to=>'estadisticas#periodo_examenes'
post 'estadisticas/estadisticas_lectivo', :to=>'estadisticas#estadisticas_lectivo'
post 'estadisticas/estadisticas_examenes', :to=>'estadisticas#estadisticas_examenes'
post 'estadisticas/borrar_historico_lectivo', :to=>'estadisticas#borrar_historico_lectivo'
post 'estadisticas/borrar_historico_examenes', :to=>'estadisticas#borrar_historico_examenes'
post 'periodos/cambia_admision', :to=>'periodos#cambia_admision'
post 'periodos/cambia_activo', :to=>'periodos#cambia_activo'
post 'periodos/enviar_correo_lectivo_on', :to=>'periodos#enviar_correo_lectivo_on'
post 'periodos/enviar_correo_activo_off', :to=>'periodos#enviar_correo_activo_off'
post 'periodos/enviar_correo_activo_on', :to=>'periodos#enviar_correo_activo_on'
post 'periodos/enviar_correo_lectivo_off', :to=>'periodos#enviar_correo_lectivo_off'
post 'periodos/grabar_historico', :to=>'periodos#grabar_historico'
post 'periodos/grabar_historico_examen', :to=>'periodos#grabar_historico_examen'
post 'solicitar/anadir', :to=>'solicitar#anadir'
get 'solicitar/eliminar', :to=>'solicitar#eliminar'
post 'asignaturas/combo_por_titulacion', :to => 'asignaturas#combo_por_titulacion'
post 'asignaturas/combo_por_descripcion', :to => 'recursos#combo_por_descripcion'
post 'asignaturas/combo_por_nivel', :to => 'asignaturas#combo_por_nivel'
post 'usuarios/listar', :to => 'usuarios#listar'
post 'asignaturas/listar', :to => 'asignaturas#listar'
post 'recursos/listar', :to => 'recursos#listar'
post 'solicitudlabs/listar', :to => 'solicitudlabs#listar'
post 'solicitudlabexas/listar', :to => 'solicitudlabexas#listar'
post 'solicitudlabexas/borrarSolicitudes', :to => 'solicitudlabexas#borrarSolicitudes'
post 'solicitudusuariolabexas/listar', :to => 'solicitudusuariolabexas#listar'
post 'solicitudrecursos/listar', :to => 'solicitudrecursos#listar'
post 'solicitudrecursos/borrar_reservas', :to => 'solicitudrecursos#borrar_reservas'
post 'solicitudrecursousuarios/listar', :to => 'solicitudrecursousuarios#listar'
post 'solicitudrecursousuarios/buscar', :to => 'solicitudrecursousuarios#buscar'
post 'solicitudusuariolabs/listar', :to => 'solicitudusuariolabs#listar'
post 'solicitudusuariolabs/crear', :to => 'solicitudusuariolabs#create'
post 'solicitudusuariolabs/update', :to => 'solicitudusuariolabs#update'
post 'solicitudusuariolabs/copy', :to => 'solicitudusuariolabs#copy'

post 'solicitudrecursos/buscar', :to => 'solicitudrecursos#buscar'
post 'solicitudrecursos/crear', :to => 'solicitudrecursos#create'
post 'solicitudrecursos/borra', :to => 'solicitudrecursos#borra'
post 'solicitudrecursousuarios/borra', :to => 'solicitudrecursousuarios#borra'
post 'solicitudrecursousuarios/crear', :to => 'solicitudrecursousuarios#create'

post 'solicitar/eliminar', :to => 'solicitar#eliminar'
post 'asignacions/anadirListaExterna', :to => 'asignacions#anadirListaExterna'

post 'asignaciondefs/anadirListaExterna', :to => 'asignaciondefs#anadirListaExterna'
post 'asignacions/mover', :to => 'asignacions#mover'
get 'asignacions/revisar', :to => 'asignacions#revisar'
get 'asignacions/asignar', :to => 'asignacions#asignar'
get 'asignacions/asignar_iniciar', :to => 'asignacions#asignar_iniciar'
get 'asignacions/asignar_continuar', :to => 'asignacions#asignar_continuar'
get 'asignacions/grabar_asignacion', :to => 'asignacions#grabar_asignacion'
get 'asignaciondefs/grabar_asignacion', :to => 'asignaciondefs#grabar_asignacion'
get 'asignaciondefs/consulta', :to => 'asignaciondefs#consulta'
get 'asignaciondefs/asigna_directa', :to => 'asignaciondefs#asigna_directa'
post 'asignaciondefs/graba', :to => 'asignaciondefs#graba'
post 'asignacions/graba', :to => 'asignacions#graba'
post 'asignaciondefs/getAsignacion', :to => 'asignaciondefs#getAsignacion'
post 'asignacions/getAsignacion', :to => 'asignacions#getAsignacion'
post 'asignaciondefs/borradirasignada', :to => 'asignaciondefs#borradirasignada'
post 'asignacions/borranormal', :to => 'asignacions#borranormal'
post 'asignaciondefs/borranormalasignada', :to => 'asignaciondefs#borranormalasignada'
post 'asignaciondefs/actualizar', :to => 'asignaciondefs#actualizar'
post 'asignacions/actualizar', :to => 'asignacions#actualizar'
get 'listado/asignacion_lectivo_impresa', :to => 'listado#asignacion_lectivo_impresa'
get 'listado/asignacion_examenes_impresa', :to => 'listado#asignacion_examenes_impresa'
get 'listado/asignacion_lectivo_usuario_impresa', :to => 'listado#asignacion_lectivo_usuario_impresa'
get 'listado/asignacion_examenes_usuario_impresa', :to => 'listado#asignacion_examenes_usuario_impresa'
get 'listado/solicitud_lectivo_impresa', :to => 'listado#solicitud_lectivo_impresa'
get 'listado/solicitud_examen_impresa', :to => 'listado#solicitud_examen_impresa'
get 'listado/solicitud_recurso_impresa', :to => 'listado#solicitud_recurso_impresa'
get 'listado/estadistica_lectivo_impresa', :to => 'listado#estadistica_lectivo_impresa'
get 'listado/estadistica_examenes_impresa', :to => 'listado#estadistica_examenes_impresa'

get 'consultasasig/porusuario', :to => 'consultasasig#porusuario'
get 'consultasasig/general', :to => 'consultasasig#general'
get 'consultasasig/labgeneral', :to => 'consultasasig#labgeneral'
get 'consultasasig/labporusuario', :to => 'consultasasig#labporusuario'
post 'consultasasig/listar', :to => 'consultasasig#listar'

post 'asignacionexas/mover', :to => 'asignacionexas#mover'
get 'asignacionexas/revisar', :to => 'asignacionexas#revisar'
get 'asignacionexas/asignar', :to => 'asignacionexas#asignar'
get 'asignacionexas/asignar_iniciar', :to => 'asignacionexas#asignar_iniciar'
get 'asignacionexas/asignar_continuar', :to => 'asignacionexas#asignar_continuar'
get 'asignacionexas/grabar_asignacion', :to => 'asignacionexas#grabar_asignacion'
get 'asignacionexas/consulta', :to => 'asignacionexas#consulta'
get 'asignacionexas/asigna_directa', :to => 'asignacionexas#asigna_directa'
post 'asignacionexas/graba', :to => 'asignacionexas#graba'
post 'asignacionexas/borradir', :to => 'asignacionexas#borradir'
post 'asignacionexas/borradirasignada', :to => 'asignacionexas#borradirasignada'
post 'asignacionexas/borranormal', :to => 'asignacionexas#borranormal'
post 'asignacionexas/borranormalasignada', :to => 'asignacionexas#borranormalasignada'
post 'asignacionexas/listar', :to => 'asignacionexas#listar'
post 'asignacions/destroy', :to => 'asignacions#destroy'
post 'asignaciondefs/destroy', :to => 'asignaciondefs#destroy'
post 'asignaciondefs/pegar', :to => 'asignaciondefs#pegar'
post 'asignacions/pegar', :to => 'asignacions#pegar'
get 'sessions/destroy', :to => 'sessions#destroy'

end

app/controllers/solicitudusuariolabexas_controller.rb
class SolicitudusuariolabexasController < ApplicationController
  # GET /solicitudlabexas
  # GET /solicitudlabexas.xml

  before_action :login_requerido,:usuario?

  include SolicitudesHelper


  def index
    
    getIndexView
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @solicitudlabexas }
    end
  end

  # GET /solicitudlabexas/new
  # GET /solicitudlabexas/new.xml
  def new
    @solicitudlabexa = Solicitudlabexa.new
    @solicitudlabexa.asignatura=Asignatura.new
     @solicitudlabexa.fecha=Date.today
    @solicitudlabexa.preferencias=""
    session[:titulacion]=Titulacion.first
    session[:nivel]=Asignatura::CURSO.first
    @action="create"
    getViewModel
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @solicitudlabexa }
    end
  end

  # GET /solicitudlabs/1/edit
  def edit
    @solicitudlabexa = Solicitudlabexa.find(params[:id])
    @action="update" 
    getViewModel
       
    #@asignatura=Asignatura.find(@solicitudlabexa.asignatura_id)
    #@solicitudlabexa.fecha=fecha_europea(@solicitudlabexa.fecha)
   # @asignaturas=Asignatura.where('titulacion_id = ? and curso = ?', @asignatura.titulacion_id, @solicitudlabexa.asignatura.curso).order("nombre_asig").to_a
    #@usuarios=Usuario.order("apellidos").to_a.reject{|u| u.identificador=="anonimo"}
  end

  # POST /solicitudlabs
  # POST /solicitudlabs.xml
  def saveObject(params)
 
    @solicitudlabexa.usuario_id = @usuario_actual.id
    if params[:asignatura].nil?
      @solicitudlabexa.asignatura=Asignatura.new
      @solicitudlabexa.asignatura.titulacion_id=params[:titulacion][:titulacion_id] unless params[:titulacion].nil?
      @solicitudlabexa.asignatura.curso=params[:nivel]
      @solicitudlabexa.asignatura.id=0
    else
      @solicitudlabexa.asignatura_id = params[:asignatura][:id].to_i
    end

    logger.debug "Asignaturaaass"+@solicitudlabexa.asignatura.titulacion_id.to_s
    
    @solicitudlabexa.fechasol=Date.today
    @solicitudlabexa.npuestos=params[:npuestos]
    @solicitudlabexa.curso=params[:nivel].to_s == '0' ? 'optativa' : params[:nivel].to_s
    @solicitudlabexa.comentarios=Iconv.conv('ascii//translit//ignore', 'utf-8', params[:comentarios].to_s)
    @solicitudlabexa.horaini=params[:horaini][:comienzo]
    @solicitudlabexa.horafin=params[:horafin][:fin]
    @solicitudlabexa.asignado="N"
    
    pref=""
    @especiales=Laboratorio.where('especial=?',"t").to_a 
    for especial in @especiales do
      nombre=especial.ssoo.to_s
      if params[:"#{nombre}"].to_s!='in'
        pref+=especial.nombre_lab.to_s+'-'+nombre+'-'+params[:"#{nombre}"]+";"
      end
    end
    @solicitudlabexa.preferencias=pref
     if params[:fecha]=~ /[0-3]?[0-9]\-[0-1]?[0-9]\-[0-9]{4}/
      @solicitudlabexa.fecha=formato_europeo(params[:fecha])
    else
      @solicitudlabexa.fecha=nil
    end 
  end

  def create   
    @solicitudlabexa = Solicitudlabexa.new
    saveObject(params)
     
    @solicitudlabexa.tipo="P"
    getViewModel
    respond_to do |format|
      if @solicitudlabexa.save      
         CorreoTecnicos::emitesolicitudexamen(@solicitudlabexa,params[:fecha],"","Nueva ").deliver_later                                  
        @solicitudlabexas = Solicitudlabexa.where("usuario_id = ?",@usuario_actual.id).to_a
        
        format.html { redirect_to :action => "index" }
        format.xml  { render :xml => @solicitudlabexas, :status => :created, :location => @solicitudlabexas }
      else
        @action="create"
        format.html { render :action => "new" }
        format.xml  { render :xml => @solicitudlabexas.errors, :status => :unprocessable_entity }
      end
    end
  end

  def getViewModel
    @especiales=Laboratorio.where('especial=?',"t").to_a 
    @titulaciones=Titulacion.order("nombre").to_a
     if (@solicitudlabexa.asignatura_id == nil)
      #@solicitudlabexa.asignatura_id=0
      if (Asignatura::CURSO).first=="optativa"
         as='0'
      else 
         as=Asignatura::CURSO.first
      end
       @asignaturas=Asignatura.where('titulacion_id = ? and curso = ?',@titulaciones.first.id,as).to_a
   else
       @asignatura=Asignatura.find(@solicitudlabexa.asignatura_id)
       @asignaturas=Asignatura.where('titulacion_id = ? and curso = ?', @asignatura.titulacion_id, @solicitudlabexa.asignatura.curso).order("nombre_asig").to_a
   end
    
    @puestos=Laboratorio.find_by_sql(["select distinct(puestos) from laboratorios order by puestos"]).map{|l| l.puestos}
    @horas=Horasexa.where('en_uso=?',"t").order("id").to_a
  end
  # PUT /solicitudlabexas/1
  # PUT /solicitudlabexas/1.xml

 def update
    @solicitudlabexa = Solicitudlabexa.find(params[:id])
    saveObject(params)
    getViewModel
    respond_to do |format|

        if @solicitudlabexa.save
          CorreoTecnicos::emitesolicitudexamen(@solicitudlabexa,params[:fecha],"","Cambios en ").deliver_later   
          getIndexView
          format.html { redirect_to :action => "index" }
          format.xml  { head :ok }
      else
         @action="update"
        format.html { render :action => "edit"}
        format.xml  { render :xml => @solicitudlabexa.errors, :status => :unprocessable_entity }
   end
 end
  end

  # DELETE /solicitudlabexas/1
  # DELETE /solicitudlabexas/1.xml
 def destroy
    @solicitudlabexa = Solicitudlabexa.find(params[:id])
    CorreoTecnicos::emitesolicitudexamen(@solicitudlabexa,params[:fecha],"","Borrado de ").deliver_later   
    @solicitudlabexa.destroy
    respond_to do |format|
      format.html { redirect_to(solicitudusuariolabexas_url) }
      format.xml  { head :ok }
    end
  end

 
def listar  #está incompleto.....
    cadena=params[:query]
    if cadena=~/\d{2}\-\d{2}\-(\d{4})/
        cadena=cadena.split('-')[2]+'-'+cadena.split('-')[1]+'-'+cadena.split('-')[0]
    else
        if cadena=~/\d{2}\-\d{2}/ || cadena=~/\d{2}\-\d{4}/
           cadena=cadena.split('-')[1]+'-'+cadena.split('-')[0]
        else
           if cadena=~/\d{2}\-/
               cadena='-'+cadena.split('-')[0]
           end
        end
    end
    
    cadena=(cadena.nil?)? "%" : "%#{cadena}%"
    
    @asignaturas=Asignatura.where("nombre_asig || abrevia_asig || curso LIKE ?",cadena).to_a
    codigos_a=@asignaturas.map { |t| t.id}
    @labs_especiales=Laboratorio.where("ssoo || nombre_lab like ? and especial=?",cadena,"t").to_a
    nombre_l=@labs_especiales.map {|l| l.nombre_lab+'-'+l.ssoo+'-'+'si'+';'}
    nombre_l=nombre_l+@labs_especiales.map {|l| l.nombre_lab+'-'+l.ssoo+'-'+'no'+';'}
    @solicitudlabexas=Solicitudlabexa.where("usuario_id == ? and (npuestos || curso || fecha || fechasol LIKE ?  or asignatura_id in (?) or preferencias in (?))", session[:user_id], cadena, codigos_a, nombre_l).to_a
    @solicitudlabexas=@solicitudlabexas.select{|s| isLabRequestCurrent?(s)}
    @cuenta=@solicitudlabexas.size

    respond_to {|format| format.js }

end

def getIndexView

      @solicitudlabexas= Solicitudlabexa.where("usuario_id = ?",@usuario_actual.id).order("fecha").to_a
      @solicitudlabexas = @solicitudlabexas.select{|s| isLabRequestCurrentCuatrimester?(s, false)}
      @cuenta=@solicitudlabexas.size
end

private
def solicitudlabexas_params
  params.require(:solicitudlabexa).permit()
end

 
end

app/views/solicitudusuariolabexas/_items_lista.html.erb
<% nasignacionexa=Asignacionlabexa.all.size %>
<% nasignacionexadef=Asignacionlabexadef.all.size %>
<% total=nasignacionexa+nasignacionexadef %>

<%= form_tag new_solicitudusuariolabexa_path, :method=>:get do -%>
        <%= submit_tag "Nueva solicitud", :class=>"botonindexsearch" %>
<% end -%>

<% if @solicitudlabexas %>
    <% periodo=Periodo.where("tipo = ? AND (activo = ? OR admision = ?)","Examenes","t","t").order("inicio DESC").first %>
    <div id="nom_periodo">
    <% if !periodo.nil? %><!-- si se esta en un periodo de asignaciones activadas o adjudicadas-->
      <%= periodo.nombre %>
    <% else %>
      No est&aacute; abierta la admisi&oacute;n de solicitudes
    <% end %>
    </div>
     <p>Solicitudes : <%= @cuenta %></p>
     <p><%= image_tag ("bg_separ.gif") %></p>
     <% if @cuenta!=0 %>

       <table >

        <tr>
         <th> </th>
         <th class="cien">Fecha sol.</th>  
         <th class="cientocincuenta">Asignatura</th>
         <th class="cincuenta">Curso</th>
         <th class="cincuenta">Equ.</th>
         <th class="cien">Fecha</th>
         <th>Tramo horario</th>
         <th class="cien">Soft.</th>
         <th class="cientoveinticinco">Elecci&oacute;n equipos</th>       
        </tr>

        <tr>
         <% if @solicitudlabexas.empty? %>
           <td><%= h "No hay solicitudes de laboratorios emitidas" %></td>
         <% end %> 
        </tr>

        <% @solicitudlabexas.each do |i| %>
        <tr valign="top" class="<%=cycle('linea-impar','linea-par') %>">
         
         <td class="icono"><% if (i.tipo!="X" and !periodo.nil? and total==0) and i.asignado!="D" %><!-- X: asignaciones directas de admin -->
                             <%= link_to image_tag("Editar.png", :border=>0),  edit_solicitudusuariolabexa_path(i) %>
                           <% else %>
                             <% if i.asignado=="D" %>
                               <%= image_tag("mark.png", :border=>0, :size=>"24x24") %>
                             <% else %>
                              <% if i.asignado=="N" %>
                                <%= link_to image_tag("Editar.png", :border=>0),  edit_solicitudusuariolabexa_path(i) %>
                              <% end %>
                            <% end %>
                           <% end %></td>
         <td><%= fecha_europea(i.fechasol) %></td>  
         <td><% asig=Asignatura.find(i.asignatura_id) %>
             <a onmouseover=ShowContent('asignatura<%=i.id.to_s%>'); return true;
   			   onmouseout=HideContent('asignatura<%=i.id.to_s%>'); return true;>
                           <div id="asignatura<%=i.id.to_s %>" 
				style='display:none;position:absolute;
      					border-style: solid;
      					background-color: white;width:300px;
      					padding: 5px;';>
                                        <%= asig.nombre_asig %><br/><!-- nombre completo de la asignatura -->
                                        <%="Titulacion :"+asig.titulacion.abrevia %>
			    </div>
             <%= asig.abrevia_asig %></td><!-- nombre abreviado de la asignatura -->
         <td style="text-align:center"><% if i.curso.to_s=="sin curso" %>
                                          <%= "-" %>
                                       <% else %>
                                          <%= i.curso %>
                                       <% end %></td>
         <td style="text-align:center"><%= i.npuestos %></td>
         <td><%= fecha_europea(i.fecha) %></td>
         
         <td><%= i.horaini+" - "+i.horafin %></td>
         <td style="text-align:center"><a onmouseover=ShowContent("flotante<%=i.id.to_s%>"); return true;
   			   onmouseout=HideContent("flotante<%=i.id.to_s%>"); return true;>
                            <div id="flotante<%=i.id.to_s%>" 
				style='display:none;position:absolute;
      					border-style: solid;
      					background-color: white;
      					padding: 5px;';>
                                        <%=i.comentarios %><!-- se visualiza el comentario completo -->
			    </div>
			    <%="SI" unless i.comentarios.to_s=="" %></a><!-- si hay comentarios, se indica --></td>
         <td><% @preferencias=i.preferencias.split(";") unless i.preferencias.nil? %>  
            <table>
              <%=render(:partial => "/solicitudlabs/tramo_preferencia", :collection=> @preferencias ) %>
            </table></td>    
         <td class="icono"><% if (i.tipo!="X" and !periodo.nil? and total==0)  and i.asignado!="N" %><!-- solicitudes de asignaciones directas de admin -->
                             <%= link_to image_tag("borrar.png", :border=>0), solicitudusuariolabexa_path(i),
                              data: { confirm: '¿Seguro que desea eliminar la solicitud?'}, :method => :delete %>
                           <% else %>
                              <% if i.tipo=="X" %>
                                  Asignaci&oacute;n directa
                              <% end %>
                           <% end %>
                           </td> 
        </tr>
        <% end %><!-- de @solicitudusuariolabexas.each -->
       </table>
     <% end %><!-- de if @cuenta!=0 -->  
<% end %><!-- de if @solicitudlabexas -->

app/views/solicitudusuariolabexas/edit.html.erb
<%= render :partial => "new_or_edit", :locals => { :titulo => "Editando solicitud de laboratorio para período de exámenes", :submit_name => "Guardar cambios", :error_message => "Imposible modificar solicitud debido a:" } %>

app/views/solicitudusuariolabexas/index.html.erb
<div id="central" >
    <p id=titulo>GESTOR DE RECURSOS<br/>
       <%= image_tag ("pointer.gif") %>Solicitudes de laboratorios para ex&aacute;menes
    </p>
    <div id="recuadro">
       <div id="lista-gestion">
          <p><%= image_tag ("bg_separ.gif") %></p>
          <div id="busqueda">
           <table>
            <tr>
              <td><%= image_tag("search.png") %></td>
              <td>Buscar  : 
              <td><%= text_field_tag "query" %>
            </tr>
           </table>
          </div><!-- de busqueda -->
          <div id="tabla"><%= render :partial => "items_lista" %></div> 
       </div><!-- de lista-gestion -->
    </div><!-- de recuadro -->
</div><!-- de central -->

<script type="text/javascript">

$(function()
  {
    $("#query").keyup(function()
      {
        var url="/solicitudusuariolabexas/listar";
        var query=$("#query").val();

        $.ajax({
          type:"POST",
          url:url,
          data:{query:query}
        });
      });
  });
</script>

app/views/solicitudusuariolabexas/listar.js.erb
$("#tabla").html(" <%= escape_javascript (render( :partial => '/solicitudusuariolabexas/items_lista', 
                  :object => @solicitudlabexas))%>"); 

app/views/solicitudusuariolabexas/new.html.erb
<%= render :partial => "new_or_edit", :locals => { :titulo => "Creando nueva solicitud de laboratorio para período de exámenes", :submit_name => "Crear", :error_message => "Imposible crear nueva solicitud debido a:" } %>