config/routes.rb
Gestorlcc::Application.routes.draw do

  resources :periodos,:peticionlabs,:solicitudlabs, :solicitudlabexas

  resources :dias, :horarios, :horasexas, :peticions, :solicitudrecursos

  resources :titulacions,:recursos, :laboratorios, :asignaturas,:usuarios
  resource :solicitar, :session, :inicio, :userinicio, :dato, :solicitudrecurso
  resources :solicitudrecursousuarios, :solicitudusuariolabs,:solicitudusuariolabexas

  get 'usuarios/:id/cambiar', :to => 'usuarios#cambiar' 

  

root :to => 'sessions#index'

get 'anonimo/new', :to=>'anonimo#new'
get 'anonimo/general', :to=>'anonimo#general'
get 'anonimo/labgeneral', :to=>'anonimo#labgeneral'
get 'estadisticas/periodo_lectivo', :to=>'estadisticas#periodo_lectivo'
get 'estadisticas/periodo_examenes', :to=>'estadisticas#periodo_examenes'
post 'estadisticas/estadisticas_lectivo', :to=>'estadisticas#estadisticas_lectivo'
post 'estadisticas/estadisticas_examenes', :to=>'estadisticas#estadisticas_examenes'
post 'estadisticas/borrar_historico_lectivo', :to=>'estadisticas#borrar_historico_lectivo'
post 'estadisticas/borrar_historico_examenes', :to=>'estadisticas#borrar_historico_examenes'
post 'periodos/cambia_admision', :to=>'periodos#cambia_admision'
post 'periodos/cambia_activo', :to=>'periodos#cambia_activo'
post 'periodos/enviar_correo_lectivo_on', :to=>'periodos#enviar_correo_lectivo_on'
post 'periodos/enviar_correo_activo_off', :to=>'periodos#enviar_correo_activo_off'
post 'periodos/enviar_correo_activo_on', :to=>'periodos#enviar_correo_activo_on'
post 'periodos/enviar_correo_lectivo_off', :to=>'periodos#enviar_correo_lectivo_off'
post 'periodos/grabar_historico', :to=>'periodos#grabar_historico'
post 'periodos/grabar_historico_examen', :to=>'periodos#grabar_historico_examen'
post 'solicitar/anadir', :to=>'solicitar#anadir'
get 'solicitar/eliminar', :to=>'solicitar#eliminar'
post 'asignaturas/combo_por_titulacion', :to => 'asignaturas#combo_por_titulacion'
post 'asignaturas/combo_por_descripcion', :to => 'recursos#combo_por_descripcion'
post 'asignaturas/combo_por_nivel', :to => 'asignaturas#combo_por_nivel'
post 'usuarios/listar', :to => 'usuarios#listar'
post 'asignaturas/listar', :to => 'asignaturas#listar'
post 'recursos/listar', :to => 'recursos#listar'
post 'solicitudlabs/listar', :to => 'solicitudlabs#listar'
post 'solicitudlabexas/listar', :to => 'solicitudlabexas#listar'
post 'solicitudlabexas/borrarSolicitudes', :to => 'solicitudlabexas#borrarSolicitudes'
post 'solicitudusuariolabexas/listar', :to => 'solicitudusuariolabexas#listar'
post 'solicitudrecursos/listar', :to => 'solicitudrecursos#listar'
post 'solicitudrecursos/borrar_reservas', :to => 'solicitudrecursos#borrar_reservas'
post 'solicitudrecursousuarios/listar', :to => 'solicitudrecursousuarios#listar'
post 'solicitudrecursousuarios/buscar', :to => 'solicitudrecursousuarios#buscar'
post 'solicitudusuariolabs/listar', :to => 'solicitudusuariolabs#listar'
post 'solicitudusuariolabs/crear', :to => 'solicitudusuariolabs#create'
post 'solicitudusuariolabs/update', :to => 'solicitudusuariolabs#update'
post 'solicitudusuariolabs/copy', :to => 'solicitudusuariolabs#copy'

post 'solicitudrecursos/buscar', :to => 'solicitudrecursos#buscar'
post 'solicitudrecursos/crear', :to => 'solicitudrecursos#create'
post 'solicitudrecursos/borra', :to => 'solicitudrecursos#borra'
post 'solicitudrecursousuarios/borra', :to => 'solicitudrecursousuarios#borra'
post 'solicitudrecursousuarios/crear', :to => 'solicitudrecursousuarios#create'

post 'solicitar/eliminar', :to => 'solicitar#eliminar'
post 'asignacions/anadirListaExterna', :to => 'asignacions#anadirListaExterna'

post 'asignaciondefs/anadirListaExterna', :to => 'asignaciondefs#anadirListaExterna'
post 'asignacions/mover', :to => 'asignacions#mover'
get 'asignacions/revisar', :to => 'asignacions#revisar'
get 'asignacions/asignar', :to => 'asignacions#asignar'
get 'asignacions/asignar_iniciar', :to => 'asignacions#asignar_iniciar'
get 'asignacions/asignar_continuar', :to => 'asignacions#asignar_continuar'
get 'asignacions/grabar_asignacion', :to => 'asignacions#grabar_asignacion'
get 'asignaciondefs/grabar_asignacion', :to => 'asignaciondefs#grabar_asignacion'
get 'asignaciondefs/consulta', :to => 'asignaciondefs#consulta'
get 'asignaciondefs/asigna_directa', :to => 'asignaciondefs#asigna_directa'
post 'asignaciondefs/graba', :to => 'asignaciondefs#graba'
post 'asignacions/graba', :to => 'asignacions#graba'
post 'asignaciondefs/getAsignacion', :to => 'asignaciondefs#getAsignacion'
post 'asignacions/getAsignacion', :to => 'asignacions#getAsignacion'
post 'asignaciondefs/borradirasignada', :to => 'asignaciondefs#borradirasignada'
post 'asignacions/borranormal', :to => 'asignacions#borranormal'
post 'asignaciondefs/borranormalasignada', :to => 'asignaciondefs#borranormalasignada'
post 'asignaciondefs/actualizar', :to => 'asignaciondefs#actualizar'
post 'asignacions/actualizar', :to => 'asignacions#actualizar'
get 'listado/asignacion_lectivo_impresa', :to => 'listado#asignacion_lectivo_impresa'
get 'listado/asignacion_examenes_impresa', :to => 'listado#asignacion_examenes_impresa'
get 'listado/asignacion_lectivo_usuario_impresa', :to => 'listado#asignacion_lectivo_usuario_impresa'
get 'listado/asignacion_examenes_usuario_impresa', :to => 'listado#asignacion_examenes_usuario_impresa'
get 'listado/solicitud_lectivo_impresa', :to => 'listado#solicitud_lectivo_impresa'
get 'listado/solicitud_examen_impresa', :to => 'listado#solicitud_examen_impresa'
get 'listado/solicitud_recurso_impresa', :to => 'listado#solicitud_recurso_impresa'
get 'listado/estadistica_lectivo_impresa', :to => 'listado#estadistica_lectivo_impresa'
get 'listado/estadistica_examenes_impresa', :to => 'listado#estadistica_examenes_impresa'

get 'consultasasig/porusuario', :to => 'consultasasig#porusuario'
get 'consultasasig/general', :to => 'consultasasig#general'
get 'consultasasig/labgeneral', :to => 'consultasasig#labgeneral'
get 'consultasasig/labporusuario', :to => 'consultasasig#labporusuario'
post 'consultasasig/listar', :to => 'consultasasig#listar'

post 'asignacionexas/mover', :to => 'asignacionexas#mover'
get 'asignacionexas/revisar', :to => 'asignacionexas#revisar'
get 'asignacionexas/asignar', :to => 'asignacionexas#asignar'
get 'asignacionexas/asignar_iniciar', :to => 'asignacionexas#asignar_iniciar'
get 'asignacionexas/asignar_continuar', :to => 'asignacionexas#asignar_continuar'
get 'asignacionexas/grabar_asignacion', :to => 'asignacionexas#grabar_asignacion'
get 'asignacionexas/consulta', :to => 'asignacionexas#consulta'
get 'asignacionexas/asigna_directa', :to => 'asignacionexas#asigna_directa'
post 'asignacionexas/graba', :to => 'asignacionexas#graba'
post 'asignacionexas/borradir', :to => 'asignacionexas#borradir'
post 'asignacionexas/borradirasignada', :to => 'asignacionexas#borradirasignada'
post 'asignacionexas/borranormal', :to => 'asignacionexas#borranormal'
post 'asignacionexas/borranormalasignada', :to => 'asignacionexas#borranormalasignada'
post 'asignacionexas/listar', :to => 'asignacionexas#listar'
post 'asignacions/destroy', :to => 'asignacions#destroy'
post 'asignaciondefs/destroy', :to => 'asignaciondefs#destroy'
post 'asignaciondefs/pegar', :to => 'asignaciondefs#pegar'
post 'asignacions/pegar', :to => 'asignacions#pegar'
get 'sessions/destroy', :to => 'sessions#destroy'

end

app/controllers/solicitudrecursousuarios_controller.rb
class SolicitudrecursousuariosController < ApplicationController
 # GET /solicitudrecursos
  # GET /solicitudrecursos.xml

  before_action :login_requerido,:usuario?

  include SolicitudrecursosHelper


  def index
    
    getIndexView

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @solicitudrecursousuarios }
    end
  end

  # GET /solicitudrecursos/new
  # GET /solicitudrecursos/new.xml
 
  def new  # modificacion para transacciones
    @solicitudrecurso = Solicitudrecurso.new  
   
    #identifico los tipos distintos de recurso
    @tipos = Recurso.all.map{ |i| i.descripcion }.uniq
    
    # cargo los dias y horas posibles para los select
    @dias=Dia.where('en_uso = ?',"t").to_a
    @horas=Horario.where('en_uso = ?',"t").to_a

    #obtengo y formateo la fecha actual
    @dia=@solicitudrecurso.fechareserva=formato_europeo(Date.today)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @solicitudrecurso }
    end
  end

  # GET /solicitudrecursos/1/edit
  def edit
 
# NECESITO UN DRYYYY!!!!!
    @solicitudrecurso = Solicitudrecurso.find(params[:id])
    usuario=Usuario.find(@solicitudrecurso.usuario_id)
    @usuario=usuario.apellidos+", "+usuario.nombre   
    @dia=Date.today.strftime("%d-%m-%Y")   
    @nfechareserva=@solicitudrecurso.fechareserva.strftime("%d-%m-%Y")
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @solicitudrecurso }
    end
    
  end

  # POST /solicitudrecursos
  # POST /solicitudrecursos.xml


  def create
    @solicitudrecurso = Solicitudrecurso.new
    @solicitudrecurso.tipo=params[:tipo]
    @solicitudrecurso.fechasol=Date.today
    @solicitudrecurso.horaini=params[:horai]
    @solicitudrecurso.horafin=params[:horaf]
    @solicitudrecurso.fechareserva=session[:fechares]
    @solicitudrecurso.usuario_id=session[:user_id]
    @solicitudrecurso.motivos=params[:motivos]
    
       
      if @solicitudrecurso.save
        familia=Recurso.where("identificador = ?",@solicitudrecurso.tipo).first.descripcion
        @recs=Recurso.where('descripcion = ? and disponible = ?',familia,"t").to_a
        @ids=@recs.map {|r| r.identificador}
        #session[:fechares]=params[:fecha]
        dia=formato_europeo(session[:fechares])
        #alreves=session[:fechares].to_s.split('-')
        #dia=alreves[2]+"-"+alreves[1]+"-"+alreves[0]
        @reservas = Solicitudrecurso.where('tipo in (?) and fechareserva = ?', @ids,dia).to_a

        respond_to do |format|
          format.js
        end
      end


  end


  # PUT /solicitudrecursos/1
  # PUT /solicitudrecursos/1.xml
  def update
    @solicitudrecurso = Solicitudrecurso.find(params[:id])
    

    respond_to do |format|
  
      if @solicitudrecurso.update_attributes(:motivos => params[:motivos])
               
        getIndexView
        format.html { render :action => "index" }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @solicitudrecurso.errors, :status => :unprocessable_entity }
      end
    
    end
  end



  # DELETE /solicitudrecursos/1
  # DELETE /solicitudrecursos/1.xml
  def destroy
   @solicitudrecurso = Solicitudrecurso.find(params[:id])
   @solicitudrecursos= Solicitudrecurso.where("usuario_id = ?",@usuario_actual.id).to_a 
   @solicitudrecurso.destroy
    
    respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { head :ok }
    end
  end

  def borra
    @solicitudrecurso = Solicitudrecurso.find(params[:reserva])
    familia=Recurso.where("identificador = ?",@solicitudrecurso.tipo).first.descripcion
    @solicitudrecurso.destroy
    @recs=Recurso.where('descripcion = ? and disponible = ?',familia,"t").to_a
    @ids=@recs.map {|r| r.identificador}
    #session[:fechares]=params[:fecha]
    dia=formato_europeo(session[:fechares])
    #alreves=session[:fechares].to_s.split('-')
    #dia=alreves[2]+"-"+alreves[1]+"-"+alreves[0]
    @reservas = Solicitudrecurso.where( 'tipo in (?) and fechareserva = ?', @ids,dia).to_a

    respond_to do |format|
      format.js
    end
  end

  def listar
    cadena=params[:query]
    if cadena=~/\d{2}\-\d{2}\-(\d{4})/
        cadena=cadena.split('-')[2]+'-'+cadena.split('-')[1]+'-'+cadena.split('-')[0]
    else
        if cadena=~/\d{2}\-\d{2}/ || cadena=~/\d{2}\-\d{4}/
           cadena=cadena.split('-')[1]+'-'+cadena.split('-')[0]
        else
           if cadena=~/\d{2}\-/
               cadena='-'+cadena.split('-')[0]
           end
        end
    end

    cadena=(cadena.nil?)? "%" : "%#{cadena}%"
    
    @recs=Recurso.where("descripcion || identificador LIKE ?", cadena).to_a
    recs=@recs.map {|r| r.identificador}
    
      
    @solicitudrecursos=Solicitudrecurso.where("usuario_id = ? and (fechareserva ||  fechasol || motivos LIKE ?  or  tipo in (?))",session[:user_id],cadena,recs).to_a
    @solicitudrecursos = @solicitudrecursos.select{|s| isLabRequestCurrent?(s)}
    @cuenta=@solicitudrecursos.size
  end


  def buscar
   dia=params[:fecha].to_date

   if dia.wday!=0 and dia>=Date.today # no comprueba si el dia es posterior a hoy o no es domingo
     @recs=Recurso.where('descripcion = ? and disponible = ?',params[:tipo_descripcion],"t").to_a
     @ids=@recs.map {|r| r.identificador}
     session[:fechares]=params[:fecha]
     dia=formato_europeo(params[:fecha])
     #alreves=params[:fecha].to_s.split('-')
     #dia=alreves[2]+"-"+alreves[1]+"-"+alreves[0]
     @reservas = Solicitudrecurso.where('tipo in (?) and fechareserva = ?',@ids,dia).to_a
   else
     @festivo=1
   end
  end

  def getIndexView

      @solicitudrecursos= Solicitudrecurso.where("usuario_id = ?",session[:user_id]).order("fechareserva").to_a
      @solicitudrecursos = @solicitudrecursos.select{|s| isLabRequestCurrent?(s)}
      @cuenta=@solicitudrecursos.size
  end

end

app/helpers/solicitudrecursousuarios_helper.rb
module SolicitudrecursousuariosHelper
end

app/views/solicitudrecursousuarios/_items_lista.html.erb
<%= form_tag new_solicitudrecursousuario_path, :method=>:get do -%>
        <%= submit_tag "Consulta/reserva", :class=>"botonindexsearch" %>
<% end -%>

<% if @solicitudrecursos %>
   <p>Reservas : <%=@cuenta %></p>
   <p><%= image_tag ("bg_separ.gif") %></p>
   <% if @cuenta!=0 %>
    <table>
     <tr>
       <th> </th>
       <th class="cien">Fecha reserva</th>  
       <th class="doscientoscincuenta">Recurso</th>
       <th class="cien">Dia reservado</th>
       <th class="cientocincuenta">Tramo horario</th>
       <th class="doscientos">Motivos</th>
       <th class="doscientoscincuenta">Aviso</th>
     </tr>
     <% @solicitudrecursos.each do |i| %>
     <tr valign="top" class="<%=cycle('linea-impar','linea-par') %>">
       <td class="icono">
           <% if i.fechareserva>=Date.today %>
                <%= link_to image_tag("Editar.png", :border=>0),  edit_solicitudrecursousuario_path(i) %>
           <% end %></td> 
       <td><%= i.fechasol.strftime("%d-%m-%Y")  %></td>  
       <td><% familia=Recurso.find_by_identificador(i.tipo) %>
           <%= familia.descripcion+" : "+i.tipo %></td>
       <td><%= i.fechareserva.strftime("%d-%m-%Y")  %></td>
       <td style="text-align:center"><%= i.horaini+"-"+i.horafin %></td>
       <td><%= i.motivos %></td>
       <td><%= familia.aviso %></td>
       <td class="icono">
           <% if i.fechareserva>=Date.today %>
                <%= link_to image_tag("borrar.png", :border=>0), solicitudrecursousuario_path(i), 
                             data:{ confirm: '¿Seguro que desea eliminar la reserva?'}, :method => :delete %>
           <% end %></td> 
     </tr>
     <% end %><!-- de @solicitudrecursos.each -->
    </table>
   <% end %><!-- de if @cuenta!=0 --> 
<% end %><!-- de @solicitudrecursos -->

app/views/solicitudrecursousuarios/_recurso_reservado.html.erb
<%    @dias=Dia.where('en_uso=?',"t").to_a  %>

<% if @festivo %>
    <div id="errores">     
       <div id="errorExplanation">
          <p>Imposible efectuar reserva de recurso:</p>
          <ul><li>El d&iacute;a seleccionado es festivo o pasado</li>
          </ul>
       </div>     
    </div>
<% else %>

 <table id="horario">
  <tr>
    <th>
    <% for  r in @recs %>
           <th style="padding: 5px 0px;">

             <a onmouseover=ShowContent("recurso<%= r.id.to_s %>"); return true;
   			   onmouseout=HideContent("recurso<%=r.id.to_s %>"); return true;>
                           <div id="recurso<%=r.id.to_s %>" 
				style='display:none;position:absolute;
      					border-style: solid;
      					background-color: white;
      					padding: 5px;
                                        width:300px;';>
                                        <%= r.caracteristicas %>
			    </div>
              <%= r.descripcion+" : "+r.identificador %></a></th>
              <% end %>
      </tr>
  <% fila=0 %>
  <% for i in 0..Recurso::NUMHORAS %>
    <% fila+=1 %>
    <tr>
      <th><%= Recurso::HORAS[i]+"-"+Recurso::HORAS[i+1] %></th>
          <% columna=0 %>
          <% for r in @recs %>
             <% columna+=1 %>
	     <% reserva=@reservas.select{|m| m.tipo==r.identificador && m.horaini==Recurso::HORAS[i]}   %>
             <% if !reserva.empty? %>
                <td id="celda_ocupada" style="text-align:center"><% profesor=reserva[0].usuario %>
                      <a onmouseover=ShowContent("flotante<%=fila.to_s+columna.to_s%>"); return true;
   			   onmouseout=HideContent("flotante<%=fila.to_s+columna.to_s%>"); return true; >
                            <div id="flotante<%=fila.to_s+columna.to_s%>" 
				style='display:none;position:absolute;
      					border-style: solid;
      					background-color: white;
      					padding: 5px;';>
                                        <%=profesor.nombre+' '+profesor.apellidos%><br> 
       					Despacho: <%= profesor.despacho %><br>
                                        Telefono: <%= profesor.telefono %><br>
                                        Email: <%= profesor.email %>
			    </div><!-- datos detallados de quien ocupa el recurso -->
			    <%=profesor.nombre+' '+profesor.apellidos%><!-- nombre y apellidos de quien ocupa el recurso -->
                            <% if profesor.id==session[:user_id] %><!-- puede anular sus reservas -->
                               <% formid2="formborra"+fila.to_s+columna.to_s %>
			       <div id="formid2" >
                                 <%= hidden_field_tag "reserva", value=reserva[0].id %>
                               </div>
                               <% if Date.today <=reserva[0].fechareserva %>         
			          <%= link_to image_tag("borrar.png", :border=>0,:height=>16,:width=>16,:style=>'cursor:pointer'),"#",:name => "borrar" %>
                               <% end %>
                            <% end %></a></td>
             <% else %>
                 <td id="celda_libre" style="text-align:center">
                       <% formid="form"+fila.to_s+columna.to_s %>
		       <div id="formid">
			   <a onclick=ShowContent("flotanteform<%=fila.to_s+columna.to_s%>"); return true; style='cursor:pointer'>Reservar</a>

                             <div id="flotanteform<%=fila.to_s+columna.to_s%>" 
				         style='display:none;position:absolute;
      					        border-style: solid;
      					        background-color: #f6ecd5;
      					        padding: 5px;';>
                                                <table class=flotante><!-- formulario de reserva -->
                                                  <tr>
                                                   <td></td>
                                                   <td align=right valign=top>
                                                    <a href="#" onclick="HideContent('flotanteform<%=fila.to_s+columna.to_s%>')">
                                                    <%=image_tag("icon_close.png",:border=>0,
                                                        :style=>'cursor:pointer')%>
                                                    </a>
                                                   </td>
                                                  </tr>
                                                  <tr>
                                                   <td>Motivos </td>
                                                   <td> <%= text_area_tag "motivos",nil,:cols=>30,:rows=>3 %></td> 
                                                 </tr>                                              
                                        	 <%= hidden_field_tag "tipo", value=r.identificador %>
                                        	 <%= hidden_field_tag "horai", value=Recurso::HORAS[i] %>
                                        	 <%= hidden_field_tag "horaf", value=Recurso::HORAS[i+1] %>
                                        	 <%= hidden_field_tag "fechasol",value=Date.today %>
						 <tr>
                                                   <td></td>
                                                   <td><input data-form="flotanteform<%=fila.to_s+columna.to_s%>" type="button" name="reservar" value="Reservar"/>
                                                   </td>
                                                 </tr>
                                                </table>
                                  </div><!-- de flotanteform -->
                            </div><!-- de formid -->
                    </td>
             <% end %><!-- de if !reserva.empty? -->   
          <% end %><!-- de for r -->
    </tr>
  <% end %><!-- de for i -->
  </table>
  <%= flash.now[:notice] %>
<% end %><!-- de if @festivo -->


<script type="text/javascript">

$(function()
  {
    $("a[name=borrar]").click(function()
    {
      var mensaje="¿Seguro que desea eliminar la reserva?";
      if(confirm(mensaje))
      {
        var url="/solicitudrecursousuarios/borra";
        var data=$(this).parent().find("input[name=reserva]").val();
        $.ajax({
          type:"POST",
          url:url,
          data:{reserva:data}
        });
      }
    });

    $("input[name=reservar]").click(function()
      {
          var id=$(this).data("form");
          var $this=$("#"+id);
          var url="/solicitudrecursousuarios/crear";
          var tipo=$this.find("input[name=tipo]").val();
          var motivos=$this.find("textarea[name=motivos]").val();
          var horai=$this.find("input[name=horai]").val();
          var horaf=$this.find("input[name=horaf]").val();
          var usuario=$this.find("#usuario_identificador").val();
        $.ajax({
          type:"POST",
          url:url,
          data:{tipo:tipo,motivos:motivos,horaf:horaf,horai:horai, usuario:usuario}
        });
      });
  });
</script>

app/views/solicitudrecursousuarios/_tramo_peticion.html.erb
<tr valign="top">
 <td width=60><%= tramo_peticion.diasemana %></td>  
 <td width=30><%= tramo_peticion.horaini %></td> 
 <td width=30><%= tramo_peticion.horafin %></td>    
</tr>

app/views/solicitudrecursousuarios/_tramos_peticiones.html.erb
<!-- OBTENGO LOS TRAMOS QUE HAY QUE VISUALIZAR , 0 EN PRINCIPIO-->

<% @tramos=session[:tramos_horarios].solicitudes %> 
<table id="tramos">
  <% if @tramos.empty? %>
    <tr><td><%= h "No hay tramos horarios" %></td></tr>
  <% else %>
    <%=render(:partial => "/solicitudrecursos/muestra_tramo", :collection=> @tramos) %> <!-- MUESTRO TRAMOS SI LOS HAY -->
  <% end %>
</table>

<!-- INCLUYO FALSO FORMULARIO DE CAPTACION PARA UN NUEVO TRAMO Y LO MANDO A LA ACCION DE ANADIR A CARRO -->

<div id="subformulario">

 
<table>
  <tr>
    <th>Dia semana</th>
    <th>Hora inicio </th>
    <th>Hora fin </th>
  </tr>


 <tr valign="top" >
  
    <td><%= select_tag "diasemana", options_for_select(["Lunes","Martes","Miercoles","Jueves","Viernes","Sabado"]) %>
    <td><%= select_tag "horaini", options_for_select(["8:45","9:45","10:45","11:45","12:45","13:45","14:45","15:15","16:15","17:15","18:15","19:15","20:15"]) %></td>
    <td><%= select_tag "horafin", options_for_select(["9:45","10:45","11:45","12:45","13:45","14:45","15:15","16:15","17:15","18:15","19:15","20:15","21:45"]) %></td>

<!-- PARECE QUE DA PROBLEMA EL LINK_TO_REMOTE PARECE QUE SE QUEDA EN EL CONTROLLER DE SOLICITUDRECURSO-->
<td>
<%= link_to(image_tag("mas.jpg",:border=>0),
	
       :submit   => "subformulario",
       :url      => { :controller=>:solicitar,:action => 'anadir' }, :remote => true) %>

</td></tr></table>

app/views/solicitudrecursousuarios/borra.js.erb
$('#reservas').html("<%= escape_javascript(render(:partial=>'/solicitudrecursousuarios/recurso_reservado',:object=>@reservas))%>");

app/views/solicitudrecursousuarios/buscar.js.erb
$('#reservas').html('<%= escape_javascript( render( :partial => "/solicitudrecursousuarios/recurso_reservado", :object => @recs)) %>' );

app/views/solicitudrecursousuarios/edit.html.erb
<div id="central" >
    <p>GESTOR DE RECURSOS<br/>
       <%= image_tag ("pointer.gif") %>Editando solicitud de recurso
    </p>
    <div id="recuadro">
       <p><%= image_tag ("bg_separ.gif") %></p>
       <div id="recuadro-azul" style="height:300px">
       <%= form_for @solicitudrecurso, :url => solicitudrecursousuario_path, :action=>"update", 
                  :html=> {:name => "formulario"} do |f| %>
         <dl>
          <dt>Fecha solicitud</dt>
          <dd><%= @dia %></dd>
          <dt>Usuario</dt>
          <dd><%= @usuario %></dd>
          <dt>Tipo de recurso</dt>
          <dd>
             <%= @solicitudrecurso.tipo %></dd>
          <dt>Fecha reserva</dt>
          <dd >
             <%= @nfechareserva %>  </dd>
          <dt>Motivos</dt>
          <dd onkeydown=' mostrardiv("solicitudrecurso_submit")'>
             <%= f.text_area :motivos, :rows =>4, :cols=>40, :name=>"motivos" %></dd>
          <p><%= f.submit 'Actualizar datos' %></p>
         </dl> 
        </div><!-- de recuadro-azul -->
     <div id="errores">
         <%= f.error_messages :header_message => 'Se produjeron errores en la captura de datos', 
             :message => 'Imposible modificar la  solicitud de laboratorio:'%>
         <% if flash.now[:notice] %>
           <div id="errorExplanation">
              <p>Imposible modificar la  solicitud de laboratorio:<p>
              <ul><li><%=flash.now[:notice]  %></li></ul>
           </div>
         <% end %>
     </div>
     <% end %>
    </div><!-- de recuadro -->
</div><!-- de central -->