config/routes.rb
Gestorlcc::Application.routes.draw do

  resources :periodos,:peticionlabs,:solicitudlabs, :solicitudlabexas

  resources :dias, :horarios, :horasexas, :peticions, :solicitudrecursos

  resources :titulacions,:recursos, :laboratorios, :asignaturas,:usuarios
  resource :solicitar, :session, :inicio, :userinicio, :dato, :solicitudrecurso
  resources :solicitudrecursousuarios, :solicitudusuariolabs,:solicitudusuariolabexas

  get 'usuarios/:id/cambiar', :to => 'usuarios#cambiar' 

  

root :to => 'sessions#index'

get 'anonimo/new', :to=>'anonimo#new'
get 'anonimo/general', :to=>'anonimo#general'
get 'anonimo/labgeneral', :to=>'anonimo#labgeneral'
get 'estadisticas/periodo_lectivo', :to=>'estadisticas#periodo_lectivo'
get 'estadisticas/periodo_examenes', :to=>'estadisticas#periodo_examenes'
post 'estadisticas/estadisticas_lectivo', :to=>'estadisticas#estadisticas_lectivo'
post 'estadisticas/estadisticas_examenes', :to=>'estadisticas#estadisticas_examenes'
post 'estadisticas/borrar_historico_lectivo', :to=>'estadisticas#borrar_historico_lectivo'
post 'estadisticas/borrar_historico_examenes', :to=>'estadisticas#borrar_historico_examenes'
post 'periodos/cambia_admision', :to=>'periodos#cambia_admision'
post 'periodos/cambia_activo', :to=>'periodos#cambia_activo'
post 'periodos/enviar_correo_lectivo_on', :to=>'periodos#enviar_correo_lectivo_on'
post 'periodos/enviar_correo_activo_off', :to=>'periodos#enviar_correo_activo_off'
post 'periodos/enviar_correo_activo_on', :to=>'periodos#enviar_correo_activo_on'
post 'periodos/enviar_correo_lectivo_off', :to=>'periodos#enviar_correo_lectivo_off'
post 'periodos/grabar_historico', :to=>'periodos#grabar_historico'
post 'periodos/grabar_historico_examen', :to=>'periodos#grabar_historico_examen'
post 'solicitar/anadir', :to=>'solicitar#anadir'
get 'solicitar/eliminar', :to=>'solicitar#eliminar'
post 'asignaturas/combo_por_titulacion', :to => 'asignaturas#combo_por_titulacion'
post 'asignaturas/combo_por_descripcion', :to => 'recursos#combo_por_descripcion'
post 'asignaturas/combo_por_nivel', :to => 'asignaturas#combo_por_nivel'
post 'usuarios/listar', :to => 'usuarios#listar'
post 'asignaturas/listar', :to => 'asignaturas#listar'
post 'recursos/listar', :to => 'recursos#listar'
post 'solicitudlabs/listar', :to => 'solicitudlabs#listar'
post 'solicitudlabexas/listar', :to => 'solicitudlabexas#listar'
post 'solicitudlabexas/borrarSolicitudes', :to => 'solicitudlabexas#borrarSolicitudes'
post 'solicitudusuariolabexas/listar', :to => 'solicitudusuariolabexas#listar'
post 'solicitudrecursos/listar', :to => 'solicitudrecursos#listar'
post 'solicitudrecursos/borrar_reservas', :to => 'solicitudrecursos#borrar_reservas'
post 'solicitudrecursousuarios/listar', :to => 'solicitudrecursousuarios#listar'
post 'solicitudrecursousuarios/buscar', :to => 'solicitudrecursousuarios#buscar'
post 'solicitudusuariolabs/listar', :to => 'solicitudusuariolabs#listar'
post 'solicitudusuariolabs/crear', :to => 'solicitudusuariolabs#create'
post 'solicitudusuariolabs/update', :to => 'solicitudusuariolabs#update'
post 'solicitudusuariolabs/copy', :to => 'solicitudusuariolabs#copy'

post 'solicitudrecursos/buscar', :to => 'solicitudrecursos#buscar'
post 'solicitudrecursos/crear', :to => 'solicitudrecursos#create'
post 'solicitudrecursos/borra', :to => 'solicitudrecursos#borra'
post 'solicitudrecursousuarios/borra', :to => 'solicitudrecursousuarios#borra'
post 'solicitudrecursousuarios/crear', :to => 'solicitudrecursousuarios#create'

post 'solicitar/eliminar', :to => 'solicitar#eliminar'
post 'asignacions/anadirListaExterna', :to => 'asignacions#anadirListaExterna'

post 'asignaciondefs/anadirListaExterna', :to => 'asignaciondefs#anadirListaExterna'
post 'asignacions/mover', :to => 'asignacions#mover'
get 'asignacions/revisar', :to => 'asignacions#revisar'
get 'asignacions/asignar', :to => 'asignacions#asignar'
get 'asignacions/asignar_iniciar', :to => 'asignacions#asignar_iniciar'
get 'asignacions/asignar_continuar', :to => 'asignacions#asignar_continuar'
get 'asignacions/grabar_asignacion', :to => 'asignacions#grabar_asignacion'
get 'asignaciondefs/grabar_asignacion', :to => 'asignaciondefs#grabar_asignacion'
get 'asignaciondefs/consulta', :to => 'asignaciondefs#consulta'
get 'asignaciondefs/asigna_directa', :to => 'asignaciondefs#asigna_directa'
post 'asignaciondefs/graba', :to => 'asignaciondefs#graba'
post 'asignacions/graba', :to => 'asignacions#graba'
post 'asignaciondefs/getAsignacion', :to => 'asignaciondefs#getAsignacion'
post 'asignacions/getAsignacion', :to => 'asignacions#getAsignacion'
post 'asignaciondefs/borradirasignada', :to => 'asignaciondefs#borradirasignada'
post 'asignacions/borranormal', :to => 'asignacions#borranormal'
post 'asignaciondefs/borranormalasignada', :to => 'asignaciondefs#borranormalasignada'
post 'asignaciondefs/actualizar', :to => 'asignaciondefs#actualizar'
post 'asignacions/actualizar', :to => 'asignacions#actualizar'
get 'listado/asignacion_lectivo_impresa', :to => 'listado#asignacion_lectivo_impresa'
get 'listado/asignacion_examenes_impresa', :to => 'listado#asignacion_examenes_impresa'
get 'listado/asignacion_lectivo_usuario_impresa', :to => 'listado#asignacion_lectivo_usuario_impresa'
get 'listado/asignacion_examenes_usuario_impresa', :to => 'listado#asignacion_examenes_usuario_impresa'
get 'listado/solicitud_lectivo_impresa', :to => 'listado#solicitud_lectivo_impresa'
get 'listado/solicitud_examen_impresa', :to => 'listado#solicitud_examen_impresa'
get 'listado/solicitud_recurso_impresa', :to => 'listado#solicitud_recurso_impresa'
get 'listado/estadistica_lectivo_impresa', :to => 'listado#estadistica_lectivo_impresa'
get 'listado/estadistica_examenes_impresa', :to => 'listado#estadistica_examenes_impresa'

get 'consultasasig/porusuario', :to => 'consultasasig#porusuario'
get 'consultasasig/general', :to => 'consultasasig#general'
get 'consultasasig/labgeneral', :to => 'consultasasig#labgeneral'
get 'consultasasig/labporusuario', :to => 'consultasasig#labporusuario'
post 'consultasasig/listar', :to => 'consultasasig#listar'

post 'asignacionexas/mover', :to => 'asignacionexas#mover'
get 'asignacionexas/revisar', :to => 'asignacionexas#revisar'
get 'asignacionexas/asignar', :to => 'asignacionexas#asignar'
get 'asignacionexas/asignar_iniciar', :to => 'asignacionexas#asignar_iniciar'
get 'asignacionexas/asignar_continuar', :to => 'asignacionexas#asignar_continuar'
get 'asignacionexas/grabar_asignacion', :to => 'asignacionexas#grabar_asignacion'
get 'asignacionexas/consulta', :to => 'asignacionexas#consulta'
get 'asignacionexas/asigna_directa', :to => 'asignacionexas#asigna_directa'
post 'asignacionexas/graba', :to => 'asignacionexas#graba'
post 'asignacionexas/borradir', :to => 'asignacionexas#borradir'
post 'asignacionexas/borradirasignada', :to => 'asignacionexas#borradirasignada'
post 'asignacionexas/borranormal', :to => 'asignacionexas#borranormal'
post 'asignacionexas/borranormalasignada', :to => 'asignacionexas#borranormalasignada'
post 'asignacionexas/listar', :to => 'asignacionexas#listar'
post 'asignacions/destroy', :to => 'asignacions#destroy'
post 'asignaciondefs/destroy', :to => 'asignaciondefs#destroy'
post 'asignaciondefs/pegar', :to => 'asignaciondefs#pegar'
post 'asignacions/pegar', :to => 'asignacions#pegar'
get 'sessions/destroy', :to => 'sessions#destroy'

end

app/controllers/solicitudusuariolabs_controller.rb
class SolicitudusuariolabsController < ApplicationController

   before_action :login_requerido,:usuario?
   #before_action :getIndexView, :only=> [:index,:copy]

   include SolicitudesHelper


  def index
     
    getIndexView

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @solicitudusuariolab }
    end
  end

  #método para realizar la copia de solicitudes del año anterior
  def copy
    @correotramos=""
    statusMessage=""
    statusCode=200

    periodo = getPeriodWithAdmission
    #coger las solicitudes anteriores de la asignatura seleccionada
    solicitudlabsAñoPasado = getLabRequestsLastYearForSubject(params[:asignatura])
    #coger sólo las solicitudes correspondientes al período lectivo actual con admision = true
    solicitudlabsAñoPasado = filterLabRequestsLastYearForPeriod(solicitudlabsAñoPasado, periodo)

    if(solicitudlabsAñoPasado.size == 0)
        statusCode = 500
        statusMessage = "No hay solicitudes anteriores de la asignatura seleccionada en el " + periodo.nombre
    else

        solicitudlabsAñoPasado.each do |s| 
           
          nuevaSolicitud = createNewRequest(s,periodo) 

          if (nuevaSolicitud.save)

             #crear peticiones de laboratorios para la nueva solicitud
             labPetitions = getLabPetitionsForRequest(s.id)
             labPetitions.each do |p|
                nuevaPeticionLab = createNewLabPetition(p, nuevaSolicitud.id)
                if(nuevaPeticionLab.save)
                    @correotramos+=' - '+nuevaPeticionLab.diasemana+' de '+nuevaPeticionLab.horaini+' a '+nuevaPeticionLab.horafin
                    CorreoTecnicos::emitesolicitudlectivo(nuevaSolicitud,nuevaSolicitud.fechaini.to_s,nuevaSolicitud.fechafin.to_s,@correotramos,"","Nueva ").deliver_later                        
                else
                  statusCode=500
                  statusMessage="Error en la copia de solicitudes"
                end
             end
          else 
            statusCode=500
            
            #no hace falta dar tantos detalles al usuario, basta con un mensaje indicando que hubo un error
            #nuevaSolicitud.errors.each do |attribute, error|
                #statusMessage += attribute.to_s + " " + error.to_s + "\n"
            #end
            statusMessage="Error en la copia de solicitudes"

            logger.debug nuevaSolicitud.errors.full_messages

          end 
          
        end
    end

    if statusCode == 200
       statusMessage="La copia se ha realizado con éxito"
    end

    getIndexView

    respond_to do |format| format.json {render :json => {:msg => statusMessage},:status => statusCode}  end

  end

  def edit
    
    @solicitudlab = Solicitudlab.find(params[:id])
    session[:tramos_horarios]=Solicitudhoraria.new
    session[:tramos_horarios].solicitudes=Peticionlab.where("solicitudlab_id = ? ",@solicitudlab.id).to_a 
    session[:codigo_tramo]=0
    session[:borrar]=[]
    @asignatura=Asignatura.find(@solicitudlab.asignatura_id)
    @asignaturas=Asignatura.where('titulacion_id = ? and curso = ?', @asignatura.titulacion_id, @solicitudlab.asignatura.curso).order("nombre_asig").to_a
   
    getViewModel
    respond_to do |format|
      format.html
      format.xml  { render :xml => @solicitudusuariolab }
    end


  end

def new
    @periodo=Periodo.where("admision = ? and tipo = ?",'t','Lectivo').first

    if(!@periodo.nil?)
      @solicitudlab = Solicitudlab.new
      @solicitudlab.preferencias=""
      @solicitudlab.fechasol=Date.today
      @solicitudlab.fechafin= @periodo.fin
      @solicitudlab.fechaini=@periodo.inicio
      @solicitudlab.asignatura=Asignatura.new
      if (Asignatura::CURSO).first=="optativa"
        as='0'
      else
        as=Asignatura::CURSO.first
      end
      getViewModel
      @asignaturas=Asignatura.where("titulacion_id = ? AND curso = ?",@titulaciones.first.id,as).to_a 
      session[:titulacion]=Titulacion.first
      session[:nivel]=Asignatura::CURSO.first

      # esto es para crear un carro no persistente  
      session[:tramos_horarios]=Solicitudhoraria.new
      # y una identificacion de tramos horarios para poder borrarlos individualmente. Se ira decrementando
      session[:codigo_tramo]=0
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @solicitudlab }
    end
  end

  
  def create
    @solicitudlab = Solicitudlab.new
    #if (Asignatura::CURSO).first=="optativa"
    #  as='0'
    #else
    #  as=Asignatura::CURSO.first
    #end
    saveModel(params)
    #@asignaturas=Asignatura.where("titulacion_id = ? AND curso = ?",@titulaciones.first.id,as).to_a 
# HACER UN DRYYYYYYY!!!!!
    getViewModel
    respond_to do |format|
    if session[:tramos_horarios].solicitudes.empty?           # no permitiremos una peticion sin tramos
      flash.now[:notice]="No hay tramos horarios en su peticion"
      format.html { render :action => "new" }
    else
      if @solicitudlab.save
        nuevo_id=@solicitudlab.id                       
        @tramos=session[:tramos_horarios].solicitudes
        @correotramos=''
        @tramos.each {|tramo| p=Peticionlab.new
                              p.solicitudlab_id=nuevo_id
                              p.diasemana=tramo.diasemana
                              p.horaini=tramo.horaini
                              p.horafin=tramo.horafin
                              p.save 
                              @correotramos+=' - '+p.diasemana+' de '+p.horaini+' a '+p.horafin}

      
        CorreoTecnicos::emitesolicitudlectivo(@solicitudlab,params[:fechaini],params[:fechafin],@correotramos,"","Nueva ").deliver_later                        
        @solicitudlabs = Solicitudlab.where("usuario_id = ?",@usuario_actual.id).to_a
        format.html { redirect_to :action => "index" }
        format.xml  { render :xml => @solicitudlabs, :status => :created, :location => @solicitudlabs }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @solicitudlabs.errors, :status => :unprocessable_entity }
      end
     end
    end
    
  end

def getViewModel
@titulaciones=Titulacion.order("nombre").to_a
@puestos=Laboratorio.find_by_sql(["select distinct(puestos) from laboratorios order by puestos"]).map{|l| l.puestos}
if(@solicitudlab.asignatura == nil)
  @solicitudlab.asignatura=Asignatura.new
end
@asignaturas=Asignatura.where('titulacion_id = ? and curso = ?', @solicitudlab.asignatura.titulacion_id, @solicitudlab.asignatura.curso).order("nombre_asig").to_a

end

def saveModel(params)
  @solicitudlab.usuario_id = @usuario_actual.id
  if @solicitudlab.asignatura==nil
      @solicitudlab.asignatura=Asignatura.new
  end
  @solicitudlab.asignatura_id = params[:asignatura][:id].to_i unless params[:asignatura].nil?
  @solicitudlab.asignatura.titulacion_id = params[:titulacion][:titulacion_id] unless params[:titulacion].nil?
  @solicitudlab.asignatura.curso = params[:nivel]
  @solicitudlab.curso = params[:nivel].to_s == '0' ? 'optativa' : params[:nivel].to_s
  @solicitudlab.comentarios=Iconv.conv('ascii//translit//ignore', 'utf-8', params[:comentarios].to_s)
  @solicitudlab.fechaini=params[:fechaini].to_date
  @solicitudlab.fechafin = params[:fechafin].to_date
  @solicitudlab.usuario_id = @usuario_actual.id

  @solicitudlab.npuestos = params[:npuestos]
  @solicitudlab.fechasol = Date.today
  periodoact=Periodo.where("admision = ? and tipo = ? ","t","Lectivo").first
  if periodoact.nil? # si es un user no puede cursar en periodo sin activaRRRRRRRR!!!!!!!!!
    iniperiodoact=finperiodoact=Date.today 
  else 
    iniperiodoact=periodoact.inicio
    finperiodoact=periodoact.fin
  end
  @solicitudlab.asignado="N"
   if params[:fechaini]==params[:fechafin]
       @solicitudlab.tipo="S"
    else
       if params[:fechaini]==iniperiodoact and params[:fechafin]==finperiodoact
         @solicitudlab.tipo="T"
       else
         @solicitudlab.tipo="P"
       end
    end
     pref=""
   @especiales=Laboratorio.where("especial=?","t").to_a
    for especial in @especiales do
      nombre=especial.ssoo.to_s
      if params[:"#{nombre}"].to_s!='in'
        pref+=especial.nombre_lab.to_s+'-'+nombre+'-'+params[:"#{nombre}"]+";"
      end
    end
    @solicitudlab.preferencias=pref
end

def update
    @solicitudlab = Solicitudlab.where("id = ? ",params[:solicitudlab][:id]).first
    saveModel(params)
   
    respond_to do |format|
    getViewModel
# UN DRYYY!!!!!
    if session[:tramos_horarios].solicitudes.empty?           # no permitiremos una peticion sin tramos
      flash.now[:notice]="No hay tramos horarios en su peticion"
      format.html { render :action => "edit" }
    else     
      if @solicitudlab.save

        @tramos=session[:tramos_horarios].solicitudes
        @tramos.each {|tramo| if tramo.id.to_i<0
                                p=Peticionlab.new
                                p.solicitudlab_id=@solicitudlab.id
                                p.diasemana=tramo.diasemana
                                p.horaini=tramo.horaini
                                p.horafin=tramo.horafin
                                p.save
                              end  }
        @borrados=session[:borrar]
        @borrados.each {|tramo| if tramo.to_i > 0
                                  reg=Peticionlab.find(tramo)
                                  reg.destroy
                                end } unless @borrados.empty?
        # flash.now[:notice] = 'Solicitudrecurso was successfully updated.'
        CorreoTecnicos::emitesolicitudlectivo(@solicitudlab,params[:fechaini],params[:fechafin],@correotramos,"","Cambios en ").deliver_later       
        

app/helpers/solicitudusuariolab_helper.rb
module SolicitudusuariolabHelper
end

app/views/solicitudusuariolabs/_items_lista.html.erb
<% nasig=Asignacion.all.size %>
<% nasigdef=Asignaciondef.all.size %>
<% total=nasig+nasigdef %>

<%= form_tag new_solicitudusuariolab_path, :method=>:get do -%>
    <%= submit_tag "Nueva solicitud", :class=>"botonindexsearch" %>
<% end -%>

<% if @solicitudlabs %>
    <% periodo=Periodo.where("tipo = ? AND (activo = ? OR admision = ?)","Lectivo","t","t").order("inicio DESC").first %>
    <div id="nom_periodo">
    <% if !periodo.nil? %><!-- si se esta en un periodo de asignaciones activadas o adjudicadas-->
      <%= periodo.nombre %>
    <% else %>
      No est&aacute; abierta la admisi&oacute;n de solicitudes
    <% end %>
    </div>
     <p>Solicitudes : <%=@cuenta %></p>
     <p><%= image_tag ("bg_separ.gif") %></p>
     <% if @cuenta!=0 %>
        <table >
          <tr>
            <th> </th>
            <th class="cien">Fecha sol.</th>  
            <th class="doscientos">Asignatura</th>
            <th class="cincuenta">Curso</th>
            <th class="cincuenta">Eq.</th>
            <th class="cien">Fecha inicio</th>
            <th class="cien">Fecha fin</th>
            <th >Petici&oacute;n</th>
            <th>Soft.</th>
            <th class="cientocincuenta">Tipo lab</th>
            
          </tr>
          <tr>
          <% if @solicitudlabs.empty? %>
            <td><%= "No hay solicitudes de laboratorios emitidas" %></td>
          <% end %> 
          </tr>
          <% @solicitudlabs.each do |i| %>
          <tr valign="top" class="<%=cycle('linea-impar','linea-par') %>">
            
            <td class="icono"><% if (i.tipo!="X" and !periodo.nil? and total==0) and i.asignado!="D" %>
                              <!-- solicitudes que reflejan asignaciones directas de admin o periodos no vigentes -->
                                <%= link_to image_tag("Editar.png", :border=>0),  edit_solicitudusuariolab_path(i) %>
                              <% else %>
                                <% if i.asignado=="D" %>
                                  <%= image_tag("mark.png", :border=>0, :size=>"24x24") %>
                                <% else %>
                              <% if i.asignado=="N" %>
                                <%= link_to image_tag("Editar.png", :border=>0),  edit_solicitudusuariolab_path(i) %>
                              <% end %>
                            <% end %>
                           <% end %></td>
            <td class="fecha"><%= fecha_europea(i.fechasol) %></td>  
            <td><% asig=Asignatura.find(i.asignatura_id) %>
                <a onmouseover=ShowContent("asignatura<%=i.id.to_s%>"); return true;
   			   onmouseout=HideContent("asignatura<%=i.id.to_s%>"); return true;>
                           <div id="asignatura<%=i.id.to_s %>" 
				style='display:none;position:absolute;
      					border-style: solid;
      					background-color: white;width:300px;
      					padding: 5px;';>
                                        <%= asig.nombre_asig %><br/><!-- nombre completo de la asignatura -->
                                        <%="Titulacion :"+asig.titulacion.abrevia %>
			    </div>
             <%= asig.abrevia_asig %></td><!-- nombre abreviado de la asignatura -->
            <td style="text-align:center"><% if i.curso.to_s=="sin curso" %>
                                          <%= "-" %>
                                       <% else %>
                                          <%= i.curso %>
                                       <% end %></td>
            <td style="text-align:center"><%= i.npuestos %></td>
            <td><%= fecha_europea(i.fechaini) %></td>
            <td><%= fecha_europea(i.fechafin) %></td>
            <td><% @tramos=i.peticionlab %>
                <table>
                   <%=render(:partial => "/solicitudrecursos/tramo_peticion", :collection=> @tramos ) %>
                </table>
            </td>
            <td style="text-align:center"><a onmouseover=ShowContent("flotante<%=i.id.to_s%>"); return true;
   			   onmouseout=HideContent("flotante<%=i.id.to_s%>"); return true;>
                            <div id="flotante<%=i.id.to_s%>" 
				style='display:none;position:absolute;width:200px;
      					border-style: solid;
      					background-color: white;
      					padding: 5px;';>
                                        <%=i.comentarios %>
			    </div><!-- se visualiza el comentario -->
			    <%="SI" unless i.comentarios.to_s=="" %></a><!-- se indica si hay comentario que visualizar --></td>
            <td><% @preferencias=i.preferencias.split(";") unless i.preferencias.nil? %>  
               <table>
                   <%=render(:partial => "/solicitudlabs/tramo_preferencia", :collection=> @preferencias ) %>
               </table>
            </td>           
            <td class="icono"><% if (i.tipo!="X" and !periodo.nil? and total==0) or i.asignado!="D"  %>
                              <!-- solicitudes que reflejan asignaciones directas de admin o periodos no vigentes-->
                                 <%= link_to image_tag("borrar.png", :border=>0), solicitudusuariolab_path(i), 
                                    data: { confirm: '¿Seguro que desea eliminar la solicitud?'}, :method => :delete %>
                                 <% else %>
                                   <% if i.tipo=="X" %>
                                    Asignaci&oacute;n directa
                                   <% end %>
                                 <% end %></td>  
          </tr>
       <% end %><!-- de @solicitudlabs.each -->
     </table>
   <% end %><!-- de if @cuenta!=0 -->
<% end %><!-- de if @solicitudlabs -->

app/views/solicitudusuariolabs/copy.js.erb
$("#tabla").html('<%= escape_javascript(render(:partial =>  'items_lista', :locals => {:obj => @solicitudlabs}))%>');

app/views/solicitudusuariolabs/edit.html.erb
<div id="central" >
    <p>GESTOR DE RECURSOS<br/>
       <%= image_tag ("pointer.gif") %>Editando solicitud de laboratorio para per&iacute;odo lectivo
    </p>

       <%= render :partial=> "add_or_edit", :locals => { :submit_name => "Guardar cambios", :error_message => "Imposible modificar la solicitud debido a:" }%>
</div><!-- de central -->

<script type="text/javascript">
$(function()
  {
    $("form[name=formulario]").attr("action", "/solicitudusuariolabs/update");
  });
</script>

app/views/solicitudusuariolabs/index.html.erb
<div id="central" >
    <p id=titulo>GESTOR DE RECURSOS<br/>
       <%= image_tag ("pointer.gif") %>Solicitudes de laboratorios para periodo lectivo
    </p>
    <div id="recuadro">
        <div id="lista-gestion">
            <p><%= image_tag ("bg_separ.gif") %></p>
            <div style="display:inline;">
            <div id="busqueda" style="float:left;">
               <table>
                <tr>
                  <td><%= image_tag("search.png") %></td>
                  <td>Buscar  : 
                  <td><%= text_field_tag "query" %></td>   
                </tr>
               </table>
             </div>

             <!--Si no hay solicitudes actuales, se debe mostrar la opción copiar las solicitudes del año pasado si las hubiese , { :multiple => true, :size =>3 }-->
             <%if @labRequestsAllowed and @cuenta == 0 and @numSolLabsLastYear > 0 %>
             <div style="float:left;">
              <table>
                <tr>
                  <td>    
                  <%= select_tag 'asignatura', options_for_select(@asignaturas.map {|s| [ s.asig_with_tit, s.id, {:title =>("Asignatura: " + s.nombre_asig + "\n" + "Titulación:"+s.titulacion.nombre)} ]}.uniq) %>
                  </td> 
                </tr>
                <tr> <td><input name="copyBtn" type="button" value="Recuperar solicitudes anteriores" style="width:210px;height:25px;" /></td>  </tr>
               </table>
             </div>
             <%end%>
            </div>
            <div id="errores">
       </div>

        <div id="cargando" style="text-align:center">
                  <%=image_tag("ajax-loader.gif",:border=>0) %>
        </div>

        <div id="tabla" style="float:left;">
              <%= render :partial => "items_lista" %>  
        </div> 
      </div><!-- de lista-gestion -->
     </div><!-- de recuadro -->
</div><!-- de central -->


<script type="text/javascript">
 $(function()
  {
    $("#query").keyup(function()
      {
         var url="/solicitudusuariolabs/listar";
         var query=$("#query").val();
         $.ajax({
          type:"POST",
          url:url,
          data:{query:query}
         });
      });
   eventosCopiar();
  });

function eventosCopiar()
{ 
	$("#cargando").hide();
	 $('input[name=copyBtn]').click(function () 
   { 
       $("#cargando").show();
       $.ajax({
                 dataType:"json",
                 type: "POST",
                 url: "/solicitudusuariolabs/copy",
                 data: {asignatura:$("#asignatura").val()},
                 success: function(data, textStatus)
                 {
                    $("#cargando").hide();
                    alert(data.msg);
                    location.reload();
                 },
                 error: function(data, textStatus)
                 {
                     $("#cargando").hide();
                     var error = data.responseJSON.msg
                     alert(error);
                 }
            });
    });
}

</script>

app/views/solicitudusuariolabs/listar.js.erb
$("#tabla").html("<%= escape_javascript( render :partial => '/solicitudusuariolabs/items_lista', 
                  :object => @solicitudlabs )%>");

app/views/solicitudusuariolabs/new.html.erb
<div id="central" >
   <p>GESTOR DE RECURSOS<br/>
      <%= image_tag ("pointer.gif") %>Creando solicitud de laboratorio para per&iacute;odo lectivo
   </p>
        <%= render :partial=> "add_or_edit", :locals => { :submit_name => "Crear", :error_message => "Imposible crear la solicitud debido a:" }%>
</div><!-- de central -->

<script type="text/javascript">
$(function()
  {
    $("form[name=formulario]").attr("action", "/solicitudusuariolabs/crear");;
  });
</script>