config/routes.rb
Gestorlcc::Application.routes.draw do

  resources :periodos,:peticionlabs,:solicitudlabs, :solicitudlabexas

  resources :dias, :horarios, :horasexas, :peticions, :solicitudrecursos

  resources :titulacions,:recursos, :laboratorios, :asignaturas,:usuarios
  resource :solicitar, :session, :inicio, :userinicio, :dato, :solicitudrecurso
  resources :solicitudrecursousuarios, :solicitudusuariolabs,:solicitudusuariolabexas

  get 'usuarios/:id/cambiar', :to => 'usuarios#cambiar' 

  

root :to => 'sessions#index'

get 'anonimo/new', :to=>'anonimo#new'
get 'anonimo/general', :to=>'anonimo#general'
get 'anonimo/labgeneral', :to=>'anonimo#labgeneral'
get 'estadisticas/periodo_lectivo', :to=>'estadisticas#periodo_lectivo'
get 'estadisticas/periodo_examenes', :to=>'estadisticas#periodo_examenes'
post 'estadisticas/estadisticas_lectivo', :to=>'estadisticas#estadisticas_lectivo'
post 'estadisticas/estadisticas_examenes', :to=>'estadisticas#estadisticas_examenes'
post 'estadisticas/borrar_historico_lectivo', :to=>'estadisticas#borrar_historico_lectivo'
post 'estadisticas/borrar_historico_examenes', :to=>'estadisticas#borrar_historico_examenes'
post 'periodos/cambia_admision', :to=>'periodos#cambia_admision'
post 'periodos/cambia_activo', :to=>'periodos#cambia_activo'
post 'periodos/enviar_correo_lectivo_on', :to=>'periodos#enviar_correo_lectivo_on'
post 'periodos/enviar_correo_activo_off', :to=>'periodos#enviar_correo_activo_off'
post 'periodos/enviar_correo_activo_on', :to=>'periodos#enviar_correo_activo_on'
post 'periodos/enviar_correo_lectivo_off', :to=>'periodos#enviar_correo_lectivo_off'
post 'periodos/grabar_historico', :to=>'periodos#grabar_historico'
post 'periodos/grabar_historico_examen', :to=>'periodos#grabar_historico_examen'
post 'solicitar/anadir', :to=>'solicitar#anadir'
get 'solicitar/eliminar', :to=>'solicitar#eliminar'
post 'asignaturas/combo_por_titulacion', :to => 'asignaturas#combo_por_titulacion'
post 'asignaturas/combo_por_descripcion', :to => 'recursos#combo_por_descripcion'
post 'asignaturas/combo_por_nivel', :to => 'asignaturas#combo_por_nivel'
post 'usuarios/listar', :to => 'usuarios#listar'
post 'asignaturas/listar', :to => 'asignaturas#listar'
post 'recursos/listar', :to => 'recursos#listar'
post 'solicitudlabs/listar', :to => 'solicitudlabs#listar'
post 'solicitudlabexas/listar', :to => 'solicitudlabexas#listar'
post 'solicitudlabexas/borrarSolicitudes', :to => 'solicitudlabexas#borrarSolicitudes'
post 'solicitudusuariolabexas/listar', :to => 'solicitudusuariolabexas#listar'
post 'solicitudrecursos/listar', :to => 'solicitudrecursos#listar'
post 'solicitudrecursos/borrar_reservas', :to => 'solicitudrecursos#borrar_reservas'
post 'solicitudrecursousuarios/listar', :to => 'solicitudrecursousuarios#listar'
post 'solicitudrecursousuarios/buscar', :to => 'solicitudrecursousuarios#buscar'
post 'solicitudusuariolabs/listar', :to => 'solicitudusuariolabs#listar'
post 'solicitudusuariolabs/crear', :to => 'solicitudusuariolabs#create'
post 'solicitudusuariolabs/update', :to => 'solicitudusuariolabs#update'
post 'solicitudusuariolabs/copy', :to => 'solicitudusuariolabs#copy'

post 'solicitudrecursos/buscar', :to => 'solicitudrecursos#buscar'
post 'solicitudrecursos/crear', :to => 'solicitudrecursos#create'
post 'solicitudrecursos/borra', :to => 'solicitudrecursos#borra'
post 'solicitudrecursousuarios/borra', :to => 'solicitudrecursousuarios#borra'
post 'solicitudrecursousuarios/crear', :to => 'solicitudrecursousuarios#create'

post 'solicitar/eliminar', :to => 'solicitar#eliminar'
post 'asignacions/anadirListaExterna', :to => 'asignacions#anadirListaExterna'

post 'asignaciondefs/anadirListaExterna', :to => 'asignaciondefs#anadirListaExterna'
post 'asignacions/mover', :to => 'asignacions#mover'
get 'asignacions/revisar', :to => 'asignacions#revisar'
get 'asignacions/asignar', :to => 'asignacions#asignar'
get 'asignacions/asignar_iniciar', :to => 'asignacions#asignar_iniciar'
get 'asignacions/asignar_continuar', :to => 'asignacions#asignar_continuar'
get 'asignacions/grabar_asignacion', :to => 'asignacions#grabar_asignacion'
get 'asignaciondefs/grabar_asignacion', :to => 'asignaciondefs#grabar_asignacion'
get 'asignaciondefs/consulta', :to => 'asignaciondefs#consulta'
get 'asignaciondefs/asigna_directa', :to => 'asignaciondefs#asigna_directa'
post 'asignaciondefs/graba', :to => 'asignaciondefs#graba'
post 'asignacions/graba', :to => 'asignacions#graba'
post 'asignaciondefs/getAsignacion', :to => 'asignaciondefs#getAsignacion'
post 'asignacions/getAsignacion', :to => 'asignacions#getAsignacion'
post 'asignaciondefs/borradirasignada', :to => 'asignaciondefs#borradirasignada'
post 'asignacions/borranormal', :to => 'asignacions#borranormal'
post 'asignaciondefs/borranormalasignada', :to => 'asignaciondefs#borranormalasignada'
post 'asignaciondefs/actualizar', :to => 'asignaciondefs#actualizar'
post 'asignacions/actualizar', :to => 'asignacions#actualizar'
get 'listado/asignacion_lectivo_impresa', :to => 'listado#asignacion_lectivo_impresa'
get 'listado/asignacion_examenes_impresa', :to => 'listado#asignacion_examenes_impresa'
get 'listado/asignacion_lectivo_usuario_impresa', :to => 'listado#asignacion_lectivo_usuario_impresa'
get 'listado/asignacion_examenes_usuario_impresa', :to => 'listado#asignacion_examenes_usuario_impresa'
get 'listado/solicitud_lectivo_impresa', :to => 'listado#solicitud_lectivo_impresa'
get 'listado/solicitud_examen_impresa', :to => 'listado#solicitud_examen_impresa'
get 'listado/solicitud_recurso_impresa', :to => 'listado#solicitud_recurso_impresa'
get 'listado/estadistica_lectivo_impresa', :to => 'listado#estadistica_lectivo_impresa'
get 'listado/estadistica_examenes_impresa', :to => 'listado#estadistica_examenes_impresa'

get 'consultasasig/porusuario', :to => 'consultasasig#porusuario'
get 'consultasasig/general', :to => 'consultasasig#general'
get 'consultasasig/labgeneral', :to => 'consultasasig#labgeneral'
get 'consultasasig/labporusuario', :to => 'consultasasig#labporusuario'
post 'consultasasig/listar', :to => 'consultasasig#listar'

post 'asignacionexas/mover', :to => 'asignacionexas#mover'
get 'asignacionexas/revisar', :to => 'asignacionexas#revisar'
get 'asignacionexas/asignar', :to => 'asignacionexas#asignar'
get 'asignacionexas/asignar_iniciar', :to => 'asignacionexas#asignar_iniciar'
get 'asignacionexas/asignar_continuar', :to => 'asignacionexas#asignar_continuar'
get 'asignacionexas/grabar_asignacion', :to => 'asignacionexas#grabar_asignacion'
get 'asignacionexas/consulta', :to => 'asignacionexas#consulta'
get 'asignacionexas/asigna_directa', :to => 'asignacionexas#asigna_directa'
post 'asignacionexas/graba', :to => 'asignacionexas#graba'
post 'asignacionexas/borradir', :to => 'asignacionexas#borradir'
post 'asignacionexas/borradirasignada', :to => 'asignacionexas#borradirasignada'
post 'asignacionexas/borranormal', :to => 'asignacionexas#borranormal'
post 'asignacionexas/borranormalasignada', :to => 'asignacionexas#borranormalasignada'
post 'asignacionexas/listar', :to => 'asignacionexas#listar'
post 'asignacions/destroy', :to => 'asignacions#destroy'
post 'asignaciondefs/destroy', :to => 'asignaciondefs#destroy'
post 'asignaciondefs/pegar', :to => 'asignaciondefs#pegar'
post 'asignacions/pegar', :to => 'asignacions#pegar'
get 'sessions/destroy', :to => 'sessions#destroy'

end

app/models/recurso.rb
class Recurso < ActiveRecord::Base

HORAS=["8:00","10:00","12:00","14:00","16:00","18:00","20:00","22:00"]
NUMHORAS=6

  validates_uniqueness_of :identificador,
                          :message => ': Ya se encuentra registrado ese valor'

  validates_presence_of :identificador,  :descripcion, :caracteristicas,
                        :message => ': no puede estar en blanco'
end

app/controllers/recursos_controller.rb
class RecursosController < ApplicationController
  # GET /recursos
  # GET /recursos.xml
before_action :login_requerido, :admin?

  def index
    @recursos = Recurso.order("descripcion").to_a 
    @cuenta=@recursos.size

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recursos }
    end
  end


  # GET /recursos/new
  # GET /recursos/new.xml
  def new
    @recurso = Recurso.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recurso }
    end
  end

  # GET /recursos/1/edit
  def edit
    @recurso = Recurso.find(params[:id])
  end

  # POST /recursos
  # POST /recursos.xml
  def create
    @recurso = Recurso.new(recurso_params)

    respond_to do |format|
      if @recurso.save
      #  flash.now[:notice] = 'El recurso fue creado con &eacute;xito.'
        @recursos = Recurso.order("descripcion").to_a 
        format.html { redirect_to :action => "index" }
        format.xml  { render :xml => @recurso, :status => :created, :location => @recurso }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recurso.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recursos/1
  # PUT /recursos/1.xml
  def update
    @recurso = Recurso.find(params[:id])

    respond_to do |format|
      if @recurso.update(recurso_params)
        #flash.now[:notice] = 'El recurso fue actualizado con &eacute;xito.'
        @recursos = Recurso.order("descripcion").to_a 
        format.html { redirect_to :action => "index" }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recurso.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recursos/1
  # DELETE /recursos/1.xml
  def destroy
    @recurso = Recurso.find(params[:id])
    @recurso.destroy

    respond_to do |format|
      format.html { redirect_to(recursos_url) }
      format.xml  { head :ok }
    end
  end

  def listar
    cadena=(params[:query].nil?)? "%" : "%#{params[:query]}%"
    @recursos=Recurso.where("descripcion||identificador||caracteristicas LIKE ?",cadena).to_a
    @cuenta=@recursos.size
    logger.debug "RECURSO"
    respond_to do |format|
      format.js
    end
  end

private
def recurso_params
  params.require(:recurso).permit(:identificador, :descripcion, :caracteristicas, :disponible, :aviso)
end


end

app/helpers/recursos_helper.rb
module RecursosHelper
end

app/views/recursos/_add_or_edit.html.erb
<div id="central" >
    <p>GESTI&Oacute;N DE RECURSOS<br/>
       <%= image_tag ("pointer.gif") %>Gesti&oacute;n de archivos: <%=titulo%>
    </p>
    <div id="recuadro">
       <p><%= image_tag ("bg_separ.gif") %></p>
       <div id="recuadro-azul" style="height:275px">

        <%= form_for(@recurso) do |f| %>
         <dl>
          <dt>Identificador *</dt>
          <dd><%= f.text_field :identificador, :size=>5 %></dd>
          <dt>Tipo *</dt>
          <dd><%= f.text_field :descripcion, :size=>25 %></dd>
          <dt>Caracter&iacute;sticas *</dt>
          <dd><%= f.text_field :caracteristicas, :cols=>30, :rows=>3 %></dd>
          <dt>Disponible?</dt>
          <dd><%= f.check_box :disponible, :size=>2 %></dd>
          <dt>Aviso</dt>
          <dd><%= f.text_area :aviso, :cols=>30, :rows=>3 %></dd>
          <p><%= f.submit submit_name, :class=>"boton"%></p>
        </dl>
      </div><!-- de recuadro-azul -->

      <div id="errores">
         <%= f.error_messages :header_message => 'Se produjeron errores en la captura de datos', 
             :message => error_message%>
      </div>

      <% end %><!-- de form_for -->

    </div><!-- de recuadro -->
</div><!-- de central -->

app/views/recursos/_combo_por_descripcion.html.erb
<%= for reserva in @reservas %>
     reserva.tipo
<% end %>

app/views/recursos/_items_lista.html.erb
<% nsol=Solicitudlab.all.size %>
<% nsolexa=Solicitudlabexa.all.size %>
<% nasig=Asignacion.all.size %>
<% nasigdef=Asignaciondef.all.size %>
<% nasignacionexa=Asignacionlabexa.all.size %>
<% nasignacionexadef=Asignacionlabexadef.all.size %>
<% total=nsol+nsolexa+nasig+nasigdef+nasignacionexa+nasignacionexadef %>




<%= form_tag new_recurso_path, :method=>:get do -%>
      <%= submit_tag "Nuevo recurso", :class=>"botonindexsearch" %>
<% end -%>

<% if @recursos %>
   <p>Recursos : <%=@cuenta %></p>
   <p><%= image_tag ("bg_separ.gif") %></p>

   <% if @cuenta!=0 %>
     <table>
      <tr>
        <th> </th>
        <th class="cincuenta">Identificador</th>
        <th class="doscientos">Tipo</th>
        <th class="doscientos">Caracter&iacute;sticas</th>
        <th class="cincuenta">Dispon.</th>
        <th class="cientocincuenta">Aviso usuarios</th>
      </tr>

      <% @recursos.each do |i| %>

      <tr valign="top" class="<%=cycle('linea-impar','linea-par') %>">
        <td class="icono"><%= link_to image_tag("Editar.png", :border=>0), edit_recurso_path(i) %></td> 
        <td><%= i.identificador %></td>
        <td><%= i.descripcion %></td>
        <td><%= i.caracteristicas %></td>
        <td><%= "SI" unless !i.disponible? %></td>
        <td><%= i.aviso %></td>
        <td class="icono">
        <% if total==0 %>
          <%= link_to image_tag("borrar.png", :border=>0), i, 
          data: { confirm: '¿Seguro que desea eliminar el recurso '+i.identificador+'?'}, :method => :delete %>
        <% end %></td> 
      </tr>
      <% end %><!-- de @recursos.each -->
    </table>
   <% end %><!-- de if @cuenta!=0 -->

   <p>
<% end %><!-- de @recursos -->

app/views/recursos/_recurso_reservado.html.erb
<% for reserva in @reservas %>
     <%= reserva.tipo %>
<% end %>

app/views/recursos/edit.html.erb
<%= render :partial => "add_or_edit", :locals => { :titulo => "Editando recurso", :submit_name => "Guardar cambios", :error_message => "Imposible modificar el recurso debido a:" } %>

app/views/recursos/index.html.erb
<div id="central" >
   <p id="titulo">GESTOR DE RECURSOS<br/>
      <%= image_tag ("pointer.gif") %>Gesti&oacute;n de archivos: Otros recursos
   </p>
   <div id="recuadro">
      <div id="lista-gestion">
        <p><%= image_tag ("bg_separ.gif") %></p>

        <div id="busqueda">
         <table>
          <tr>
           <td><%= image_tag("search.png") %></td>
           <td>Buscar  : 
           <td><%= text_field_tag "query" %>         
            
          </tr>
         </table>
        </div><!-- de busqueda -->

        <div id="tabla"><%= render :partial => "items_lista" %></div> 

      </div><!-- de lista-gestion -->
    </div><!-- de titulo -->
</div><!-- de central -->



<script type="text/javascript">
$(function()
  {
    $("#query").keyup(function()
      {

        var url="/recursos/listar";
        $.ajax({
          type:"POST",
          url:url,
          data:{query:$("#query").val()}
        });
      });
  });
</script>

app/views/recursos/listar.js.erb
$("#tabla").html("<%= escape_javascript( render(:partial=>'/recursos/items_lista',:object=>@recursos))%>");

app/views/recursos/new.html.erb
<%= render :partial => "add_or_edit", :locals => { :titulo => "Creando nuevo recurso", :submit_name => "Crear",
	:error_message => "Imposible crear nuevo recurso debido a:" } %>